# Copyright Kani Contributors
# SPDX-License-Identifier: Apache-2.0 OR MIT
name: Kani Action Check
on: pull_request

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Ensure that the Kani action continues to work
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Kani with invalid version
        id: set_error
        runs: |
          output=$(./src/install-kani.sh "0.47.0")
          echo "MY_VARIABLE=$output" >> $GITHUB_ENV
        continue-on-error: true  # Continue to the next steps even if this job fails

      - name: Debug previous step
        id: debug_step
        run: echo "The selected color is $MY_VARIABLE"

      - name: Run Kani with older version
        uses: ./ # Uses the action in the root directory
        with:
          working-directory: tests/cargo-kani/simple-lib
          kani-version: '0.33.0'
      - name: Run Kani
        uses: ./ # Uses the action in the root directory
        with:
          working-directory: tests/cargo-kani/simple-lib
      - name: Test ProfProof within Kani Action
        uses: ./
        with:
          working-directory: tests/cargo-kani/proptest-lib
          args: --tests
          enable-propproof: true
