# Copyright Kani Contributors
# SPDX-License-Identifier: Apache-2.0 OR MIT
name: Kani Action Check
on: pull_request

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Ensure that the Kani action continues to work
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Kani with invalid version
        id: set_error
        run: |
          output=$(./src/install-kani.sh "0.47.0")
          echo "The output is: $output"
        continue-on-error: true  # Continue to the next steps even if this job fails

    - name: Debug Step
      run: |
        # Check if error.log exists
        if [ -f error.log ]; then
          # Read the error message from the file
          error_message=$(cat error.log)
          echo "Error from Step 2: $error_message"
        else
          echo "No error message found."
        fi

      - name: Run Kani with older version
        uses: ./ # Uses the action in the root directory
        with:
          working-directory: tests/cargo-kani/simple-lib
          kani-version: '0.33.0'
      - name: Run Kani
        uses: ./ # Uses the action in the root directory
        with:
          working-directory: tests/cargo-kani/simple-lib
      - name: Test ProfProof within Kani Action
        uses: ./
        with:
          working-directory: tests/cargo-kani/proptest-lib
          args: --tests
          enable-propproof: true
